name: diyocean
channels:
  - conda-forge
  #- defaults
dependencies:
  - python=3.11
  - xarray
  - pandas
  - gsw
  - numpydoc
  - sphinx
  #- ipython
  - jupyter
  - matplotlib
  #- pandoc
  - pip
  - pip:
    - docrep
    - nbsphinx
    - sphinxcontrib-apidoc
    - sphinx-book-theme
    #- pangeo-sphinx-book-theme
    - sphinx-copybutton
    - sphinxcontrib-srclinks
    - sphinx-panels
    - myst-nb
